"""
Generate 30 demo businesses in Catanduanes for testing
"""
import uuid
from datetime import datetime, timedelta
from database import get_neo4j_db, safe_run
from app import create_app

def generate_businesses():
    """Generate 30 businesses in Catanduanes"""
    
    # Create Flask app context
    app = create_app()
    
    with app.app_context():
        businesses = [
        {
            'id': str(uuid.uuid4()),
            'name': 'Virac IT Solutions',
            'description': 'Leading IT company offering web development, mobile apps, and IT consulting services to businesses in Catanduanes.',
            'category': 'technology',
            'address': 'Rizal Street, Virac, Catanduanes',
            'latitude': 13.5809,
            'longitude': 124.3842,
            'phone': '0528891234',
            'email': 'info@viracit.com',
            'website': 'https://viracit.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-001',
            'permit_file': 'businesses/permits/virac-it.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=30)).isoformat(),
            'rating': 4.8,
            'review_count': 12
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Coastal Restaurant',
            'description': 'Seafood restaurant with fresh daily catch, traditional Filipino dishes, and stunning ocean views.',
            'category': 'restaurant',
            'address': 'Baywalk, Virac, Catanduanes',
            'latitude': 13.5820,
            'longitude': 124.3830,
            'phone': '0528892000',
            'email': 'dining@coastalrest.com',
            'website': 'https://coastalrest.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-002',
            'permit_file': 'businesses/permits/coastal-rest.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=25)).isoformat(),
            'rating': 4.6,
            'review_count': 18
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Healthcare Center',
            'description': 'Full-service medical facility providing emergency care, outpatient services, and specialist consultations.',
            'category': 'healthcare',
            'address': 'Medical Complex, Virac, Catanduanes',
            'latitude': 13.5815,
            'longitude': 124.3850,
            'phone': '0528893000',
            'email': 'info@islandhealthcare.com',
            'website': 'https://islandhealthcare.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-003',
            'permit_file': 'businesses/permits/island-health.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=20)).isoformat(),
            'rating': 4.7,
            'review_count': 25
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Bicol Tech Academy',
            'description': 'Educational institution offering technology courses, vocational training, and professional development programs.',
            'category': 'education',
            'address': 'Education Boulevard, Virac, Catanduanes',
            'latitude': 13.5800,
            'longitude': 124.3860,
            'phone': '0528894000',
            'email': 'admission@bicoltechacademy.com',
            'website': 'https://bicoltechacademy.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-004',
            'permit_file': 'businesses/permits/bicol-tech.pdf',
            'is_verified': False,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=15)).isoformat(),
            'rating': 4.5,
            'review_count': 8
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Fresh Market',
            'description': 'Local market offering fresh vegetables, fruits, seafood, and traditional goods from local farmers.',
            'category': 'retail',
            'address': 'Main Market, Virac, Catanduanes',
            'latitude': 13.5825,
            'longitude': 124.3835,
            'phone': '0528895000',
            'email': 'info@freshmarket.com',
            'website': None,
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-005',
            'permit_file': 'businesses/permits/fresh-market.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=40)).isoformat(),
            'rating': 4.4,
            'review_count': 22
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Tours & Travel',
            'description': 'Travel agency specializing in island tours, hotel bookings, and customized vacation packages.',
            'category': 'services',
            'address': 'Tourism Center, Virac, Catanduanes',
            'latitude': 13.5810,
            'longitude': 124.3845,
            'phone': '0528896000',
            'email': 'bookings@islandtours.com',
            'website': 'https://islandtours.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-006',
            'permit_file': 'businesses/permits/island-tours.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=35)).isoformat(),
            'rating': 4.9,
            'review_count': 31
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Manufacturing Co.',
            'description': 'Textile and handicraft manufacturing company producing local products for domestic and export markets.',
            'category': 'manufacturing',
            'address': 'Industrial Zone, Virac, Catanduanes',
            'latitude': 13.5790,
            'longitude': 124.3855,
            'phone': '0528897000',
            'email': 'sales@catmfg.com',
            'website': 'https://catmfg.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-007',
            'permit_file': 'businesses/permits/cat-mfg.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=50)).isoformat(),
            'rating': 4.3,
            'review_count': 14
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catspa Wellness Resort',
            'description': 'Full-service spa and wellness resort offering massage, therapy, yoga classes, and holistic health services.',
            'category': 'services',
            'address': 'Relaxation Lane, Virac, Catanduanes',
            'latitude': 13.5818,
            'longitude': 124.3838,
            'phone': '0528898000',
            'email': 'bookings@catspa.com',
            'website': 'https://catspa.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-008',
            'permit_file': 'businesses/permits/catspa.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=22)).isoformat(),
            'rating': 4.7,
            'review_count': 19
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Peninsula Bakery & Cafe',
            'description': 'Artisanal bakery and cafe serving freshly baked goods, specialty coffee, and light meals.',
            'category': 'restaurant',
            'address': 'Downtown, Virac, Catanduanes',
            'latitude': 13.5812,
            'longitude': 124.3848,
            'phone': '0528899000',
            'email': 'info@peninsulabakery.com',
            'website': None,
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-009',
            'permit_file': 'businesses/permits/peninsula-bakery.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=18)).isoformat(),
            'rating': 4.6,
            'review_count': 27
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Autocare',
            'description': 'Full-service auto repair and maintenance center with experienced mechanics and genuine parts.',
            'category': 'services',
            'address': 'Motor District, Virac, Catanduanes',
            'latitude': 13.5805,
            'longitude': 124.3855,
            'phone': '0528900000',
            'email': 'service@catAutocare.com',
            'website': 'https://catautocare.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-010',
            'permit_file': 'businesses/permits/autocare.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=12)).isoformat(),
            'rating': 4.5,
            'review_count': 16
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Green Valley Farm',
            'description': 'Organic farm producing vegetables, fruits, and agricultural products using sustainable farming methods.',
            'category': 'retail',
            'address': 'Agricultural Area, Virac, Catanduanes',
            'latitude': 13.5830,
            'longitude': 124.3825,
            'phone': '0528901000',
            'email': 'info@greenvalleyfarm.com',
            'website': 'https://greenvalleyfarm.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-011',
            'permit_file': 'businesses/permits/green-valley.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=45)).isoformat(),
            'rating': 4.8,
            'review_count': 24
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Stellar Software Solutions',
            'description': 'Software development company specializing in custom applications, mobile development, and cloud solutions.',
            'category': 'technology',
            'address': 'Tech Hub, Virac, Catanduanes',
            'latitude': 13.5808,
            'longitude': 124.3843,
            'phone': '0528902000',
            'email': 'hello@stellarsoft.com',
            'website': 'https://stellarsoft.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-012',
            'permit_file': 'businesses/permits/stellar-soft.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=28)).isoformat(),
            'rating': 4.9,
            'review_count': 20
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Boutique Hotel',
            'description': 'Boutique hotel with comfortable rooms, restaurant, and conference facilities for business and leisure travelers.',
            'category': 'services',
            'address': 'Seafront Avenue, Virac, Catanduanes',
            'latitude': 13.5822,
            'longitude': 124.3828,
            'phone': '0528903000',
            'email': 'reservations@islandboutique.com',
            'website': 'https://islandboutique.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-013',
            'permit_file': 'businesses/permits/island-boutique.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=32)).isoformat(),
            'rating': 4.7,
            'review_count': 29
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Dental Clinic',
            'description': 'Modern dental clinic offering general dentistry, cosmetic procedures, and orthodontic treatments.',
            'category': 'healthcare',
            'address': 'Medical Center, Virac, Catanduanes',
            'latitude': 13.5816,
            'longitude': 124.3851,
            'phone': '0528904000',
            'email': 'info@catdentalclinic.com',
            'website': 'https://catdentalclinic.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-014',
            'permit_file': 'businesses/permits/dental-clinic.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=24)).isoformat(),
            'rating': 4.8,
            'review_count': 17
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Phoenix Printing Services',
            'description': 'Printing company offering offset printing, digital printing, and graphic design services for businesses.',
            'category': 'manufacturing',
            'address': 'Industrial Park, Virac, Catanduanes',
            'latitude': 13.5795,
            'longitude': 124.3860,
            'phone': '0528905000',
            'email': 'orders@phoenixprinting.com',
            'website': 'https://phoenixprinting.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-015',
            'permit_file': 'businesses/permits/phoenix-printing.pdf',
            'is_verified': False,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=10)).isoformat(),
            'rating': 4.4,
            'review_count': 11
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Ocean View Real Estate',
            'description': 'Real estate agency specializing in property sales, leasing, and property management in Catanduanes.',
            'category': 'services',
            'address': 'Business District, Virac, Catanduanes',
            'latitude': 13.5814,
            'longitude': 124.3846,
            'phone': '0528906000',
            'email': 'sales@oceanviewrealestate.com',
            'website': 'https://oceanviewrealestate.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-016',
            'permit_file': 'businesses/permits/ocean-realestate.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=38)).isoformat(),
            'rating': 4.6,
            'review_count': 15
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Gym & Fitness',
            'description': 'Modern gym facility with equipment, personal training, yoga classes, and fitness programs.',
            'category': 'services',
            'address': 'Health District, Virac, Catanduanes',
            'latitude': 13.5811,
            'longitude': 124.3844,
            'phone': '0528907000',
            'email': 'membership@islandgym.com',
            'website': 'https://islandgym.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-017',
            'permit_file': 'businesses/permits/island-gym.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=16)).isoformat(),
            'rating': 4.5,
            'review_count': 13
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Fashion House',
            'description': 'Fashion boutique featuring local designers, clothing, accessories, and custom tailoring services.',
            'category': 'retail',
            'address': 'Fashion District, Virac, Catanduanes',
            'latitude': 13.5813,
            'longitude': 124.3847,
            'phone': '0528908000',
            'email': 'info@catfashionhouse.com',
            'website': 'https://catfashionhouse.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-018',
            'permit_file': 'businesses/permits/fashion-house.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=19)).isoformat(),
            'rating': 4.7,
            'review_count': 21
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'DataWorks Analytics',
            'description': 'Business analytics and data consulting company helping businesses make data-driven decisions.',
            'category': 'technology',
            'address': 'Tech Complex, Virac, Catanduanes',
            'latitude': 13.5809,
            'longitude': 124.3842,
            'phone': '0528909000',
            'email': 'contact@dataworksanalytics.com',
            'website': 'https://dataworksanalytics.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-019',
            'permit_file': 'businesses/permits/dataworks.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=26)).isoformat(),
            'rating': 4.8,
            'review_count': 10
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Tropical Garden Landscaping',
            'description': 'Landscaping and garden design company offering landscaping, maintenance, and garden consulting.',
            'category': 'services',
            'address': 'Green District, Virac, Catanduanes',
            'latitude': 13.5821,
            'longitude': 124.3829,
            'phone': '0528910000',
            'email': 'design@tropicalgardenscape.com',
            'website': 'https://tropicalgardenscape.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-020',
            'permit_file': 'businesses/permits/tropical-garden.pdf',
            'is_verified': False,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=8)).isoformat(),
            'rating': 4.3,
            'review_count': 7
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Logistics Co.',
            'description': 'Logistics and shipping company providing cargo handling, warehousing, and distribution services.',
            'category': 'services',
            'address': 'Port Area, Virac, Catanduanes',
            'latitude': 13.5835,
            'longitude': 124.3820,
            'phone': '0528911000',
            'email': 'shipping@islandlogistics.com',
            'website': 'https://islandlogistics.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-021',
            'permit_file': 'businesses/permits/island-logistics.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=42)).isoformat(),
            'rating': 4.6,
            'review_count': 18
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Education Center',
            'description': 'Tutorial center offering tutoring services, test preparation, and educational support for students.',
            'category': 'education',
            'address': 'Learning Hub, Virac, Catanduanes',
            'latitude': 13.5801,
            'longitude': 124.3859,
            'phone': '0528912000',
            'email': 'enroll@cateducationcenter.com',
            'website': 'https://cateducationcenter.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-022',
            'permit_file': 'businesses/permits/edu-center.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=30)).isoformat(),
            'rating': 4.7,
            'review_count': 14
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Sunrise Hardware & Tools',
            'description': 'Hardware store carrying tools, equipment, building materials, and home improvement supplies.',
            'category': 'retail',
            'address': 'Commercial Street, Virac, Catanduanes',
            'latitude': 13.5807,
            'longitude': 124.3841,
            'phone': '0528913000',
            'email': 'sales@sunrisehardware.com',
            'website': 'https://sunrisehardware.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-023',
            'permit_file': 'businesses/permits/sunrise-hardware.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=36)).isoformat(),
            'rating': 4.5,
            'review_count': 19
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Photography Studio',
            'description': 'Professional photography studio offering portrait sessions, event photography, and photo editing services.',
            'category': 'services',
            'address': 'Arts District, Virac, Catanduanes',
            'latitude': 13.5815,
            'longitude': 124.3849,
            'phone': '0528914000',
            'email': 'bookings@catphotography.com',
            'website': 'https://catphotography.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-024',
            'permit_file': 'businesses/permits/photography.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=14)).isoformat(),
            'rating': 4.8,
            'review_count': 23
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Pet Care Center',
            'description': 'Veterinary clinic and pet care center offering medical services, grooming, and pet supplies.',
            'category': 'services',
            'address': 'Pet District, Virac, Catanduanes',
            'latitude': 13.5817,
            'longitude': 124.3852,
            'phone': '0528915000',
            'email': 'care@islandpetcenter.com',
            'website': 'https://islandpetcenter.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-025',
            'permit_file': 'businesses/permits/pet-center.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=21)).isoformat(),
            'rating': 4.9,
            'review_count': 26
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Solar Energy',
            'description': 'Renewable energy company providing solar panel installation and maintenance for residential and commercial use.',
            'category': 'manufacturing',
            'address': 'Energy Park, Virac, Catanduanes',
            'latitude': 13.5800,
            'longitude': 124.3861,
            'phone': '0528916000',
            'email': 'info@catsolarenergy.com',
            'website': 'https://catsolarenergy.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-026',
            'permit_file': 'businesses/permits/solar-energy.pdf',
            'is_verified': False,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=6)).isoformat(),
            'rating': 4.4,
            'review_count': 9
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Law Office',
            'description': 'Legal services firm providing corporate law, real estate, family law, and litigation services.',
            'category': 'services',
            'address': 'Legal District, Virac, Catanduanes',
            'latitude': 13.5819,
            'longitude': 124.3846,
            'phone': '0528917000',
            'email': 'counsel@catlawoffice.com',
            'website': 'https://catlawoffice.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-027',
            'permit_file': 'businesses/permits/law-office.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=48)).isoformat(),
            'rating': 4.7,
            'review_count': 12
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Island Wedding Services',
            'description': 'Wedding planning and event management company offering comprehensive wedding packages and event coordination.',
            'category': 'services',
            'address': 'Events Center, Virac, Catanduanes',
            'latitude': 13.5812,
            'longitude': 124.3844,
            'phone': '0528918000',
            'email': 'weddings@islandweddingservices.com',
            'website': 'https://islandweddingservices.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-028',
            'permit_file': 'businesses/permits/wedding-services.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=20)).isoformat(),
            'rating': 4.9,
            'review_count': 28
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'CloudNet Internet Services',
            'description': 'Internet service provider offering high-speed broadband, dedicated hosting, and network solutions.',
            'category': 'technology',
            'address': 'Tech Tower, Virac, Catanduanes',
            'latitude': 13.5810,
            'longitude': 124.3843,
            'phone': '0528919000',
            'email': 'support@cloudnetservices.com',
            'website': 'https://cloudnetservices.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-029',
            'permit_file': 'businesses/permits/cloudnet.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=34)).isoformat(),
            'rating': 4.6,
            'review_count': 20
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Catanduanes Food Products',
            'description': 'Food processing company producing packaged goods, snacks, and processed food products for local and national distribution.',
            'category': 'manufacturing',
            'address': 'Food Industry Zone, Virac, Catanduanes',
            'latitude': 13.5798,
            'longitude': 124.3858,
            'phone': '0528920000',
            'email': 'sales@catfoodproducts.com',
            'website': 'https://catfoodproducts.com',
            'owner_id': str(uuid.uuid4()),
            'permit_number': 'BP-2024-030',
            'permit_file': 'businesses/permits/food-products.pdf',
            'is_verified': True,
            'is_active': True,
            'created_at': (datetime.utcnow() - timedelta(days=44)).isoformat(),
            'rating': 4.5,
            'review_count': 16
        }
        ]
        
        db = get_neo4j_db()
        with db.session() as session:
            created_count = 0
            for business_data in businesses:
                try:
                    # Create business node
                    safe_run(session, """
                        CREATE (b:Business $business_data)
                    """, {'business_data': business_data})
                    created_count += 1
                    print(f"[OK] Created: {business_data['name']}")
                except Exception as e:
                    print(f"[ERROR] Error creating {business_data['name']}: {str(e)}")
        
        print(f"\n[SUCCESS] Successfully created {created_count}/30 businesses in Catanduanes!")

if __name__ == '__main__':
    generate_businesses()
